### ISSUE TITLE
提示在 group["params"], group["pretrain_params"] 里面有相同的参数

### ISSUE THREAD

**Issue by Decalogue** [Sanyuan-Chen/RecAdam#1]
您好!我想请教一下:
config_class, model_class, tokenizer_class, pretraining_model_class = MODEL_CLASSES[args.model_type]
这里的 pretraining_model_class 在后面的代码中没有出现,加载 new_model 和 pretrained_model 的是同一个 model_class, 这样我在别的数据集上直接改过去使用的时候发现:
for group in self.param_groups:
            for p, pp in zip(group["params"], group["pretrain_params"]):
在这里就会报错,提示在 group["params"], group["pretrain_params"] 里面有相同的参数.

请问您遇到过这样的情况吗?
多谢了!

**Comment by Sanyuan-Chen** [comment]
你好~

**Comment by Sanyuan-Chen** [comment]
你好~
1. new_model和pretrained_model确实是使用同一个model_class。new_model是我们进行fine-tune的模型，在训练中更新参数值；pretrained_model是用来指导fine-tune new_model的预训练模型，在训练中不更新参数值；两个模型拥有相同的模型架构和参数名称。感谢指出多余的变量pretraining_model_class，我们会更新将其删去。
2. 我没有遇到过类似的报错，不过还请你检查一下在初始化RecAdam优化器时，传入参数的每个group中是否group["params"] 与 group["pretrain_params"]分别是两个模型new_model和pretrained_model中所对应的相同的参数集合，而不是来自于相同的模型？

**Comment by Decalogue** [comment]
非常感谢您!
