### ISSUE TITLE
对于一个比BERT-Base参数量小的BERT，该调整哪些RecAdam的参数？

### ISSUE THREAD

**Issue by guotong1988** [Sanyuan-Chen/RecAdam#11]
比如一个3层的768-hidden_size的BERT

多谢多谢！
@Sanyuan-Chen

**Comment by Sanyuan-Chen** [comment]
你好~ 
为了将我们的方法与前人的工作进行公平合理地比较，我们在实验中使用最小的模型是通用的BERT-base模型，并没有尝试参数量更小的更特殊的模型，因此并没有相应的实验结果可以提供~ 
关于超参数的调节，如论文与Readme中所介绍，我们在实验中只对于我们RecAdam相关的超参数recadam_anneal_t0，recadam_anneal_k进行了调节，而没有去尝试调节其他的超参数。如果想要在参数量较小BERT上应用RecAdam方法，建议可以先使用vanilla fine-tuning调节一些RecAdam无关的超参数（如learning rate等），再使用我们的方法调节RecAdam相关的超参数recadam_anneal_t0与recadam_anneal_k，欢迎fork并进行一些尝试与实验~
