### ISSUE TITLE
请问 RecAdam 127 行的实现是笔误写错了吗？和论文中给出的公式逻辑不一致。

### ISSUE THREAD

**Issue by tianxin1860** [Sanyuan-Chen/RecAdam#12]
请问 RecAdam 127 行的实现是笔误写错了吗？和论文中给出的公式逻辑不一致。
![image](https://user-images.githubusercontent.com/6829601/96412216-5aff5800-121c-11eb-9f28-ae7d906d14dd.png)

**Comment by Sanyuan-Chen** [comment]
你好~
代码中127行的实现是基于论文中Algorithm 1第12行的第二个绿色阴影部分的公式：
![image](https://user-images.githubusercontent.com/22428005/96844132-baaa6d00-1481-11eb-8ebe-ace935cbd1aa.png)
与图中的公式所对应，我们默认将预训练模型参数所对应的 'group['anneal_w']' 设置为 '1'，'anneal_lambda' 对应于 'λ(t)'，'group["pretrain_cof"]' 对应于 'γ'，'p.data' 对应于 'θ'，'pp.data' 对应于 'θ∗'
