### ISSUE TITLE
如果二次惩罚和退火系数不从梯度更新算法(Adam)中解耦，效果会差别多大？

### ISSUE THREAD

**Issue by yueg** [Sanyuan-Chen/RecAdam#13]
文章中提到"当使用Adam优化器精调预训练语言模型时，我们有必要将二次惩罚和退火系数从梯度更新算法中解耦。"，请问有对比过不解耦效果会差别很大吗？
多谢！

**Comment by Sanyuan-Chen** [comment]
你好~
如我们的论文中所述，若我们需要使用自适应梯度算法（如Adam优化器）来实现论文中所介绍的预训练模拟机制和目标迁移机制，正确的实现方法应是将二次惩罚和退火系数从梯度更新算法中解耦出来。相似的做法已在AdamW论文（https://arxiv.org/abs/1711.05101） 中实现及验证，我们在实验中还没有尝试不解耦的实现方法，也没有相应的结果可以提供。
