### ISSUE TITLE
Using it for RoBERTa

### ISSUE THREAD

**Issue by yassouali** [Sanyuan-Chen/RecAdam#14]
First of all, thank you very much for providing the implementation,

I was wondering if we want to use the same approach for RoBERTa, is it possible with the repo?

**Comment by Sanyuan-Chen** [comment]
Hi~ We only conduct our RecAdam experiment with BERT and ALBERT pretrained models, so we don't have implementations for RoBERTa. However, It would be easy to apply the code for RoBERTa by switching the MODEL_CLASS. Please feel free to have a try!
