### ISSUE TITLE
pretrain与finetune的参数不一致

### ISSUE THREAD

**Issue by zjh-nudger** [Sanyuan-Chen/RecAdam#3]
请问一下，Finetune的时候会在最后加一个分类层，导致pretrain与finetune参数不一致，这种情况如何处理呢？

**Comment by Sanyuan-Chen** [comment]
你好~
由于finetune时添加的分类层在pretrained model中没有对应的参数，所以这部分额外的参数在训练时所使用的RecAdam方法会退化为Adam方法。
具体的代码实现方法可以参考我们的[GLUE example](https://github.com/Sanyuan-Chen/RecAdam/blob/0b00acef0bacc96813d510e1ecb3ad519a055660/run_glue_with_RecAdam.py#L151)，我们在初始化RecAdam优化器时，会将finetune时额外添加的参数定义为新的parameters_group，并将此group的"anneal_w"值设置为0，从而使得RecAdam优化器对此group中的参数只进行Adam的梯度更新操作，而不会加上额外的惩罚项进行多任务学习。
