### ISSUE TITLE
请问下这块的推导的出发点是？为了实现Pretraining Simulation，看不懂啊……

### ISSUE THREAD

**Issue by guotong1988** [Sanyuan-Chen/RecAdam#8]
![image](https://user-images.githubusercontent.com/4702353/93850746-55782600-fce1-11ea-93ab-dba31d47d57d.png)

@ymcui @Sanyuan-Chen 希望能讲解下，多谢多谢多谢！

**Comment by guotong1988** [comment]
大概思想貌似是和 fine-tune之前 的模型参数有关？
![image](https://user-images.githubusercontent.com/4702353/93852745-21066900-fce5-11ea-8265-ab7b8bf13f85.png)

**Comment by Sanyuan-Chen** [comment]
你好~
我们引入Pretraining Simulation的动机是：为了缓解灾难遗忘问题，我们在进行fine-tuning时希望使模型在学习downsteam task时可以同时学习pretraining tasks，然而我们在fine-tuning阶段往往没有pretraining data，而只有pretrained model。所以我们使用了一系列的近似优化方法将pretraining tasks的训练目标Loss_S近似推导为一个不依赖于pretraining data而只依赖于pretrained model的二次惩罚项。
论文中的公式推导显示了我们借鉴并基于EWC方法，通过使用Laplaces方法和模型参数之间的独立性假设，对于pretraining tasks的训练目标Loss_S进行近似优化的完整过程。
更多的关于EWC方法的介绍以及推导过程可以参考：[Overcoming catastrophic forgetting in neural networks](https://arxiv.org/abs/1612.00796), [On Quadratic Penalties in Elastic Weight Consolidation](https://arxiv.org/pdf/1712.03847.pdf), [Elastic Weight Consolidation](https://zhuanlan.zhihu.com/p/86365066).
